//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pz3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Troubles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Troubles()
        {
            this.Troubles_list = new HashSet<Troubles_list>();
        }
    
        public int Id { get; set; }
        public string Name0 { get; set; }
        public string Description0 { get; set; }
        public Nullable<int> Repair_price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Troubles_list> Troubles_list { get; set; }
    }
}
