//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pz3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Troubles_list
    {
        public int Id { get; set; }
        public Nullable<int> Report { get; set; }
        public Nullable<int> Trouble { get; set; }
    
        public virtual Reports Reports { get; set; }
        public virtual Troubles Troubles { get; set; }
    }
}
