//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pz3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public string login0 { get; set; }
        public string password0 { get; set; }
        public Nullable<int> Role0 { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
